<?php
/**
 * Reusable portfolio card.
 *
 * Accepts `post` as a WP_Post or post ID through get_template_part() args.
 *
 * @package Fahar_Theme_Child
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

$fahar_card_post = isset( $args['post'] ) ? fahar_theme_normalize_portfolio_post( $args['post'] ) : null;

if ( ! $fahar_card_post instanceof WP_Post || 'publish' !== $fahar_card_post->post_status ) {
	return;
}

$fahar_card_type = fahar_theme_get_portfolio_type( $fahar_card_post );

if ( ! $fahar_card_type ) {
	return;
}

$fahar_card_type_labels = array(
	'website'     => __( 'وب‌سایت', 'fahar-theme-child' ),
	'image'       => __( 'تصویر', 'fahar-theme-child' ),
	'video'       => __( 'ویدیو', 'fahar-theme-child' ),
	'single-page' => __( 'پروژه', 'fahar-theme-child' ),
);
$fahar_card_type_label  = isset( $fahar_card_type_labels[ $fahar_card_type ] ) ? $fahar_card_type_labels[ $fahar_card_type ] : '';

if ( ! $fahar_card_type_label ) {
	return;
}

$fahar_card_title = trim( get_the_title( $fahar_card_post ) );

if ( '' === $fahar_card_title ) {
	$fahar_card_title = __( 'نمونه‌کار بدون عنوان', 'fahar-theme-child' );
}

$fahar_card_destination   = fahar_theme_get_portfolio_destination( $fahar_card_post );
$fahar_card_url           = $fahar_card_destination['url'];
$fahar_card_is_internal   = $fahar_card_destination['is_internal'];
$fahar_card_opens_new_tab = $fahar_card_destination['opens_new_tab'];

$fahar_card_cover_id  = fahar_theme_get_portfolio_cover_id( $fahar_card_post );
$fahar_card_cover_url = fahar_theme_get_portfolio_cover_url( $fahar_card_post, 'large' );
$fahar_card_image     = '';

if ( $fahar_card_cover_id && $fahar_card_cover_url ) {
	$fahar_card_image = wp_get_attachment_image(
		$fahar_card_cover_id,
		'large',
		false,
		array(
			'class'    => 'fahar-portfolio-card__image',
			'alt'      => '',
			'decoding' => 'async',
		)
	);
}

$fahar_card_terms = fahar_theme_get_portfolio_terms( $fahar_card_post );
$fahar_card_term  = $fahar_card_terms ? reset( $fahar_card_terms ) : null;
$fahar_card_meta  = $fahar_card_term instanceof WP_Term ? $fahar_card_term->name : '';
$fahar_card_class = $fahar_card_url ? 'fahar-portfolio-card fahar-portfolio-card--linked' : 'fahar-portfolio-card';
?>
<article
	<?php post_class( $fahar_card_class, $fahar_card_post->ID ); ?>
	data-fahar-portfolio-id="<?php echo esc_attr( $fahar_card_post->ID ); ?>"
	data-fahar-portfolio-type="<?php echo esc_attr( $fahar_card_type ); ?>"
>
	<?php if ( $fahar_card_url ) : ?>
		<a
			class="fahar-portfolio-card__link"
			href="<?php echo esc_url( $fahar_card_url ); ?>"
			<?php if ( $fahar_card_is_internal ) : ?>
				data-fahar-portfolio-detail
			<?php endif; ?>
			<?php if ( $fahar_card_opens_new_tab ) : ?>
				target="_blank"
				rel="noopener noreferrer"
			<?php endif; ?>
		>
	<?php else : ?>
		<div class="fahar-portfolio-card__link fahar-portfolio-card__link--static">
	<?php endif; ?>
		<div class="fahar-portfolio-card__media">
			<?php if ( $fahar_card_image ) : ?>
				<?php echo $fahar_card_image; // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- Generated by WordPress core. ?>
			<?php else : ?>
				<div class="fahar-portfolio-card__placeholder" aria-hidden="true">
					<span><?php echo esc_html( $fahar_card_type_label ); ?></span>
				</div>
			<?php endif; ?>

			<?php if ( 'video' === $fahar_card_type ) : ?>
				<span class="fahar-portfolio-card__play" aria-hidden="true">
					<svg viewBox="0 0 24 24" focusable="false" aria-hidden="true">
						<path d="M8.5 5.8v12.4L18 12 8.5 5.8Z" fill="currentColor" />
					</svg>
				</span>
			<?php endif; ?>
		</div>

		<div class="fahar-portfolio-card__content">
			<h3 class="fahar-portfolio-card__title"><?php echo esc_html( $fahar_card_title ); ?></h3>
			<?php if ( $fahar_card_meta ) : ?>
				<div class="fahar-portfolio-card__meta"><?php echo esc_html( $fahar_card_meta ); ?></div>
			<?php endif; ?>
		</div>
	<?php if ( $fahar_card_url ) : ?>
		</a>
	<?php else : ?>
		</div>
	<?php endif; ?>
</article>
<?php
unset(
	$fahar_card_post,
	$fahar_card_type,
	$fahar_card_type_labels,
	$fahar_card_type_label,
	$fahar_card_title,
	$fahar_card_destination,
	$fahar_card_url,
	$fahar_card_is_internal,
	$fahar_card_opens_new_tab,
	$fahar_card_cover_id,
	$fahar_card_cover_url,
	$fahar_card_image,
	$fahar_card_terms,
	$fahar_card_term,
	$fahar_card_meta,
	$fahar_card_class
);
