<?php
/**
 * Render one validated Portfolio Media item.
 *
 * @package Fahar_Theme_Child
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

$fahar_media_item = isset( $args['item'] ) && is_array( $args['item'] ) ? $args['item'] : array();
$fahar_media_type = isset( $fahar_media_item['type'] ) ? sanitize_key( (string) $fahar_media_item['type'] ) : '';

if ( 'image' === $fahar_media_type ) {
	$fahar_media_image_id  = isset( $fahar_media_item['attachment_id'] ) ? absint( $fahar_media_item['attachment_id'] ) : 0;
	$fahar_media_image_id  = $fahar_media_image_id && wp_attachment_is_image( $fahar_media_image_id ) ? $fahar_media_image_id : 0;
	$fahar_media_image_url = isset( $fahar_media_item['url'] ) ? esc_url_raw( (string) $fahar_media_item['url'], array( 'http', 'https' ) ) : '';

	if ( ! $fahar_media_image_id && ! $fahar_media_image_url ) {
		return;
	}

	$fahar_media_image_alt = $fahar_media_image_id ? trim( (string) get_post_meta( $fahar_media_image_id, '_wp_attachment_image_alt', true ) ) : '';

	if ( '' === $fahar_media_image_alt && isset( $fahar_media_item['title'] ) && is_scalar( $fahar_media_item['title'] ) ) {
		$fahar_media_image_alt = trim( (string) $fahar_media_item['title'] );
	}

	$fahar_media_image_attributes = array(
		'class'    => 'fahar-portfolio-media__image',
		'alt'      => $fahar_media_image_alt,
		'decoding' => 'async',
		'sizes'    => '(min-width: 64rem) 60vw, 100vw',
	);
	$fahar_media_image_size       = isset( $fahar_media_item['size'] ) ? sanitize_key( (string) $fahar_media_item['size'] ) : 'large';
	$fahar_media_image_size       = $fahar_media_image_size ? $fahar_media_image_size : 'large';

	if ( ! empty( $fahar_media_item['primary'] ) ) {
		$fahar_media_image_attributes['loading']       = 'eager';
		$fahar_media_image_attributes['fetchpriority'] = 'high';
	} else {
		$fahar_media_image_attributes['loading'] = 'lazy';
	}

	$fahar_media_image = $fahar_media_image_id
		? wp_get_attachment_image( $fahar_media_image_id, $fahar_media_image_size, false, $fahar_media_image_attributes )
		: '';

	if ( $fahar_media_image_id && ! $fahar_media_image ) {
		return;
	}
	?>
	<figure class="fahar-portfolio-media__item fahar-portfolio-media__item--image">
		<?php if ( $fahar_media_image ) : ?>
			<?php echo $fahar_media_image; // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- Generated by WordPress core. ?>
		<?php else : ?>
			<img
				class="fahar-portfolio-media__image"
				src="<?php echo esc_url( $fahar_media_image_url ); ?>"
				alt="<?php echo esc_attr( $fahar_media_image_alt ); ?>"
				decoding="async"
				loading="<?php echo esc_attr( ! empty( $fahar_media_item['primary'] ) ? 'eager' : 'lazy' ); ?>"
				<?php if ( ! empty( $fahar_media_item['primary'] ) ) : ?>fetchpriority="high"<?php endif; ?>
				<?php if ( ! empty( $fahar_media_item['width'] ) ) : ?>width="<?php echo esc_attr( absint( $fahar_media_item['width'] ) ); ?>"<?php endif; ?>
				<?php if ( ! empty( $fahar_media_item['height'] ) ) : ?>height="<?php echo esc_attr( absint( $fahar_media_item['height'] ) ); ?>"<?php endif; ?>
			>
		<?php endif; ?>
	</figure>
	<?php
} elseif ( 'iframe' === $fahar_media_type ) {
	$fahar_media_provider = isset( $fahar_media_item['provider'] ) ? sanitize_key( (string) $fahar_media_item['provider'] ) : '';
	$fahar_media_url      = isset( $fahar_media_item['source'] ) ? esc_url_raw( (string) $fahar_media_item['source'], array( 'https' ) ) : '';
	$fahar_media_parts    = $fahar_media_url ? wp_parse_url( $fahar_media_url ) : false;
	$fahar_media_hosts    = array(
		'youtube' => 'www.youtube-nocookie.com',
		'vimeo'   => 'player.vimeo.com',
		'aparat'  => 'www.aparat.com',
	);
	$fahar_media_host     = is_array( $fahar_media_parts ) && isset( $fahar_media_parts['host'] ) ? strtolower( $fahar_media_parts['host'] ) : '';
	$fahar_media_scheme   = is_array( $fahar_media_parts ) && isset( $fahar_media_parts['scheme'] ) ? strtolower( $fahar_media_parts['scheme'] ) : '';
	$fahar_media_path     = is_array( $fahar_media_parts ) && isset( $fahar_media_parts['path'] ) ? $fahar_media_parts['path'] : '';
	$fahar_media_query    = array();
	wp_parse_str( is_array( $fahar_media_parts ) && isset( $fahar_media_parts['query'] ) ? $fahar_media_parts['query'] : '', $fahar_media_query );
	$fahar_media_paths    = array(
		'youtube' => '#^/embed/[A-Za-z0-9_-]{11}$#',
		'vimeo'   => '#^/video/\d{1,20}$#',
		'aparat'  => '#^/video/video/embed/videohash/[A-Za-z0-9_-]{1,64}/vt/frame$#',
	);

	if (
		'https' !== $fahar_media_scheme
		|| ! isset( $fahar_media_hosts[ $fahar_media_provider ], $fahar_media_paths[ $fahar_media_provider ] )
		|| $fahar_media_hosts[ $fahar_media_provider ] !== $fahar_media_host
		|| 1 !== preg_match( $fahar_media_paths[ $fahar_media_provider ], $fahar_media_path )
	) {
		return;
	}

	$fahar_media_allowed_query = array(
		'youtube' => array( 'start', 'end', 'index', 'list', 'playlist' ),
		'vimeo'   => array( 'h' ),
		'aparat'  => array(),
	);

	if ( array_diff( array_keys( $fahar_media_query ), $fahar_media_allowed_query[ $fahar_media_provider ] ) ) {
		return;
	}

	foreach ( $fahar_media_query as $fahar_media_query_key => $fahar_media_query_value ) {
		if ( ! is_scalar( $fahar_media_query_value ) ) {
			return;
		}

		$fahar_media_query_value = (string) $fahar_media_query_value;

		if (
			( in_array( $fahar_media_query_key, array( 'start', 'end', 'index' ), true ) && ! ctype_digit( $fahar_media_query_value ) )
			|| ( 'list' === $fahar_media_query_key && 1 !== preg_match( '/^[A-Za-z0-9_-]{1,128}$/', $fahar_media_query_value ) )
			|| ( 'playlist' === $fahar_media_query_key && 1 !== preg_match( '/^[A-Za-z0-9_-]{11}(?:,[A-Za-z0-9_-]{11})*$/', $fahar_media_query_value ) )
			|| ( 'h' === $fahar_media_query_key && 1 !== preg_match( '/^[A-Za-z0-9]{6,64}$/', $fahar_media_query_value ) )
		) {
			return;
		}
	}

	$fahar_media_title = isset( $fahar_media_item['title'] ) && is_scalar( $fahar_media_item['title'] ) ? trim( (string) $fahar_media_item['title'] ) : '';
	$fahar_media_poster_id = isset( $fahar_media_item['poster_attachment_id'] ) ? absint( $fahar_media_item['poster_attachment_id'] ) : 0;
	$fahar_media_poster_id = $fahar_media_poster_id && wp_attachment_is_image( $fahar_media_poster_id ) ? $fahar_media_poster_id : 0;
	$fahar_media_poster_url = isset( $fahar_media_item['poster_url'] ) ? esc_url_raw( (string) $fahar_media_item['poster_url'], array( 'http', 'https' ) ) : '';
	$fahar_media_poster = $fahar_media_poster_id
		? wp_get_attachment_image(
			$fahar_media_poster_id,
			'large',
			false,
			array(
				'class'    => 'fahar-portfolio-media__poster-image',
				'alt'      => '',
				'loading'  => 'lazy',
				'decoding' => 'async',
			)
		)
		: '';

	if ( '' === $fahar_media_title ) {
		$fahar_media_title = __( 'ویدیوی نمونه‌کار', 'fahar-theme-child' );
	}
	?>
	<figure class="fahar-portfolio-media__item fahar-portfolio-media__item--video">
		<div class="fahar-portfolio-media__embed">
			<iframe
				class="fahar-portfolio-media__iframe"
				src="<?php echo esc_url( $fahar_media_url ); ?>"
				title="<?php echo esc_attr( $fahar_media_title ); ?>"
				loading="lazy"
				allow="encrypted-media; fullscreen; picture-in-picture"
				referrerpolicy="strict-origin-when-cross-origin"
				allowfullscreen
			></iframe>
			<?php if ( $fahar_media_poster || $fahar_media_poster_url ) : ?>
				<button
					class="fahar-portfolio-media__poster"
					type="button"
					data-fahar-video-poster
					aria-label="<?php echo esc_attr( sprintf( __( 'نمایش ویدیو: %s', 'fahar-theme-child' ), $fahar_media_title ) ); ?>"
					hidden
				>
					<?php if ( $fahar_media_poster ) : ?>
						<?php echo $fahar_media_poster; // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- Generated by WordPress core. ?>
					<?php else : ?>
						<img class="fahar-portfolio-media__poster-image" src="<?php echo esc_url( $fahar_media_poster_url ); ?>" alt="" loading="lazy" decoding="async">
					<?php endif; ?>
					<span class="fahar-portfolio-media__poster-play" aria-hidden="true">
						<svg viewBox="0 0 24 24" focusable="false"><path d="m9 7 8 5-8 5Z" fill="currentColor"></path></svg>
					</span>
				</button>
			<?php endif; ?>
		</div>
	</figure>
	<?php
} elseif ( 'video' === $fahar_media_type ) {
	$fahar_media_url   = isset( $fahar_media_item['source'] ) ? esc_url_raw( (string) $fahar_media_item['source'], array( 'http', 'https' ) ) : '';
	$fahar_media_parts = $fahar_media_url ? wp_parse_url( $fahar_media_url ) : false;
	$fahar_media_path  = is_array( $fahar_media_parts ) && isset( $fahar_media_parts['path'] ) ? $fahar_media_parts['path'] : '';
	$fahar_media_ext   = strtolower( pathinfo( $fahar_media_path, PATHINFO_EXTENSION ) );

	if ( ! $fahar_media_url || ! in_array( $fahar_media_ext, wp_get_video_extensions(), true ) ) {
		return;
	}

	$fahar_media_mime  = isset( $fahar_media_item['mime'] ) ? sanitize_mime_type( (string) $fahar_media_item['mime'] ) : '';
	$fahar_media_title = isset( $fahar_media_item['title'] ) && is_scalar( $fahar_media_item['title'] ) ? trim( (string) $fahar_media_item['title'] ) : '';
	$fahar_media_poster_id = isset( $fahar_media_item['poster_attachment_id'] ) ? absint( $fahar_media_item['poster_attachment_id'] ) : 0;
	$fahar_media_poster_id = $fahar_media_poster_id && wp_attachment_is_image( $fahar_media_poster_id ) ? $fahar_media_poster_id : 0;
	$fahar_media_poster_url = $fahar_media_poster_id ? wp_get_attachment_image_url( $fahar_media_poster_id, 'large' ) : '';
	$fahar_media_poster_url = $fahar_media_poster_url ? $fahar_media_poster_url : ( isset( $fahar_media_item['poster_url'] ) ? esc_url_raw( (string) $fahar_media_item['poster_url'], array( 'http', 'https' ) ) : '' );

	if ( 0 !== strpos( $fahar_media_mime, 'video/' ) ) {
		$fahar_media_mime = '';
	}

	if ( '' === $fahar_media_title ) {
		$fahar_media_title = __( 'ویدیوی نمونه‌کار', 'fahar-theme-child' );
	}
	?>
	<figure class="fahar-portfolio-media__item fahar-portfolio-media__item--video">
		<video class="fahar-portfolio-media__video" controls preload="metadata" playsinline aria-label="<?php echo esc_attr( $fahar_media_title ); ?>"<?php if ( $fahar_media_poster_url ) : ?> poster="<?php echo esc_url( $fahar_media_poster_url ); ?>"<?php endif; ?>>
			<source
				src="<?php echo esc_url( $fahar_media_url ); ?>"
				<?php if ( $fahar_media_mime ) : ?>type="<?php echo esc_attr( $fahar_media_mime ); ?>"<?php endif; ?>
			>
		</video>
	</figure>
	<?php
}

unset(
	$fahar_media_item,
	$fahar_media_type,
	$fahar_media_image_id,
	$fahar_media_image_url,
	$fahar_media_image_alt,
	$fahar_media_image_attributes,
	$fahar_media_image_size,
	$fahar_media_image,
	$fahar_media_provider,
	$fahar_media_url,
	$fahar_media_parts,
	$fahar_media_hosts,
	$fahar_media_host,
	$fahar_media_scheme,
	$fahar_media_paths,
	$fahar_media_query,
	$fahar_media_allowed_query,
	$fahar_media_query_key,
	$fahar_media_query_value,
	$fahar_media_path,
	$fahar_media_ext,
	$fahar_media_mime,
	$fahar_media_title,
	$fahar_media_poster_id,
	$fahar_media_poster_url,
	$fahar_media_poster
);
