<?php
/**
 * Fahar desktop header fallback.
 *
 * Elementor Theme Builder owns this location when its public location API
 * successfully renders a header.
 *
 * @package Fahar_Theme_Child
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

$fahar_site_name = get_bloginfo( 'name' );
$fahar_site_name = $fahar_site_name ? $fahar_site_name : __( 'خانه', 'fahar-theme-child' );
?>
<header class="fahar-site-header">
	<div class="fahar-site-header__inner fahar-container fahar-container--wide">
		<div class="fahar-site-brand">
			<?php if ( has_custom_logo() ) : ?>
				<?php echo get_custom_logo(); // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- Generated by WordPress core. ?>
			<?php else : ?>
				<a class="fahar-site-brand__name" href="<?php echo esc_url( home_url( '/' ) ); ?>" rel="home">
					<?php echo esc_html( $fahar_site_name ); ?>
				</a>
			<?php endif; ?>
		</div>

		<?php if ( has_nav_menu( 'fahar-primary' ) ) : ?>
			<nav class="fahar-primary-nav" aria-label="<?php esc_attr_e( 'ناوبری اصلی', 'fahar-theme-child' ); ?>">
				<?php
				wp_nav_menu(
					array(
						'theme_location' => 'fahar-primary',
						'container'      => false,
						'menu_class'     => 'fahar-primary-nav__menu',
						'fallback_cb'    => false,
						'depth'          => 1,
					)
				);
				?>
			</nav>
		<?php endif; ?>

		<?php if ( has_action( 'fahar_theme_header_actions' ) ) : ?>
			<div class="fahar-site-header__actions">
				<?php
				/**
				 * Fires inside the optional Fahar header utility slot.
				 *
				 * @since 1.0.0
				 */
				do_action( 'fahar_theme_header_actions' );
				?>
			</div>
		<?php endif; ?>
	</div>
</header>
<?php unset( $fahar_site_name ); ?>
